# Generated by Django 5.1.2 on 2024-10-17 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MaintainanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SteeringAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_factory_num', models.CharField(max_length=60)),
                ('engine_factory_num', models.CharField(max_length=60)),
                ('transmission_factory_num', models.CharField(max_length=60)),
                ('steering_axle_factory_num', models.CharField(max_length=60)),
                ('driving_axle_factory_num', models.CharField(max_length=60)),
                ('delivery_contract_num', models.CharField(max_length=60)),
                ('date_of_shipment', models.DateField()),
                ('customer', models.CharField(max_length=60)),
                ('delivery_address', models.CharField(max_length=60)),
                ('equipment', models.CharField(max_length=60)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_user', to=settings.AUTH_USER_MODEL)),
                ('driving_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_control_model', to='autoservice.drivingaxlemodel')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_engine_model', to='autoservice.enginemodel')),
                ('machine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_machine_model', to='autoservice.machinemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maintainance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('operating_time', models.IntegerField()),
                ('order_id', models.CharField(max_length=60)),
                ('order_date', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_machine', to='autoservice.machine')),
                ('tm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_type', to='autoservice.maintainancetype')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_service_company', to='autoservice.servicecompany')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_service_company', to='autoservice.servicecompany'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refusal_date', models.DateField(max_length=60)),
                ('operating_time', models.IntegerField()),
                ('failure_description', models.CharField(max_length=2000)),
                ('spare_parts_used', models.CharField(max_length=2000)),
                ('recovery_date', models.DateField()),
                ('equipment_downtime', models.IntegerField()),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_failure_node', to='autoservice.failurenode')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_machine', to='autoservice.machine')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_recovery_method', to='autoservice.recoverymethod')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_service_company', to='autoservice.servicecompany')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='steering_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_lead_model', to='autoservice.steeringaxlemodel'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_transmission_model', to='autoservice.transmissionmodel'),
        ),
    ]
