# Generated by Django 5.1.2 on 2024-10-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_rename_tm_type_maintainance_maintanance_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maintainance',
            new_name='Maintenance',
        ),
        migrations.RenameModel(
            old_name='MaintainanceType',
            new_name='MaintenanceType',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='maintanance_type',
            new_name='maintenance_type',
        ),
    ]
