# Generated by Django 5.1.2 on 2024-10-24 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_rename_maintainance_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='equipment_downtime',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_machine', to='autoservice.machine'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_type', to='autoservice.maintenancetype'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_service_company', to='autoservice.servicecompany'),
        ),
    ]
